import type { Package, Testimonial, GalleryImage } from "@/lib/types";

export const packages: Package[] = [
  {
    id: "mua-akad",
    name: "ONLY MAKEUP & ATTIRE AKAD",
    price: 3500000,
    description: "Paket rias pengantin dan attire akad lengkap dengan melati fresh Sunda.",
    features: [
      "Rias Pengantin",
      "Attire Akad 1 Set",
      "Melati Fresh Sunda Siger",
      "Henna Art",
      "Softlens",
      "Fake Nails",
    ],
    categories: [
      {
        name: "MUA & ATTIRE",
        items: [
          "Rias Pengantin",
          "Attire Akad 1 Set",
          "Melati Fresh Sunda Siger",
          "Henna Art",
          "Softlens",
          "Fake Nails",
        ],
      },
    ],
  },
  {
    id: "mua-reguler",
    name: "ONLY MAKEUP & ATTIRE",
    price: 7000000,
    description: "Paket rias dan attire lengkap untuk akad dan resepsi yang elegan.",
    features: [
      "Rias Pengantin & Touch Up Makeup",
      "Attire Akad 1 Set",
      "Attire Resepsi 1 Set",
      "Melati Fresh Sunda Siger",
      "Henna Art",
      "Softlens",
      "Fake Nails",
      "Attire Orang Tua CPW & CPP",
      "Attire & Makeup Pagar Ayu 2 Orang",
      "Attire & Makeup Parasman 2 Orang",
      "Free Makeup Keluarga 2 Orang",
      "Makeup Ibu Hajat",
    ],
    categories: [
      {
        name: "MUA & ATTIRE",
        items: [
          "Rias Pengantin & Touch Up Makeup",
          "Attire Akad 1 Set",
          "Attire Resepsi 1 Set",
          "Melati Fresh Sunda Siger",
          "Henna Art",
          "Softlens",
          "Fake Nails",
          "Attire Orang Tua CPW & CPP",
          "Attire & Makeup Pagar Ayu 2 Orang",
          "Attire & Makeup Parasman 2 Orang",
          "Free Makeup Keluarga 2 Orang",
          "Makeup Ibu Hajat",
        ],
      },
    ],
  },
  {
    id: "mua-premium",
    name: "ONLY MAKEUP & ATTIRE 2",
    price: 8000000,
    description: "Paket rias dan attire premium dengan tambahan busana resepsi.",
    features: [
      "Rias Pengantin & Touch Up Makeup",
      "Attire Akad 1 Set",
      "Attire Resepsi 2 Set",
      "Melati Fresh Sunda Siger",
      "Henna Art",
      "Softlens",
      "Fake Nails",
      "Attire Orang Tua CPW & CPP",
      "Attire & Makeup Pagar Ayu 2 Orang",
      "Attire & Makeup Parasman 2 Orang",
      "Free Makeup Keluarga 2 Orang",
      "Makeup Ibu Hajat",
    ],
    categories: [
      {
        name: "MUA & ATTIRE",
        items: [
          "Rias Pengantin & Touch Up Makeup",
          "Attire Akad 1 Set",
          "Attire Resepsi 2 Set",
          "Melati Fresh Sunda Siger",
          "Henna Art",
          "Softlens",
          "Fake Nails",
          "Attire Orang Tua CPW & CPP",
          "Attire & Makeup Pagar Ayu 2 Orang",
          "Attire & Makeup Parasman 2 Orang",
          "Free Makeup Keluarga 2 Orang",
          "Makeup Ibu Hajat",
        ],
      },
    ],
  },
  {
    id: "melati-18",
    name: "ALL PACKAGE MELATI",
    price: 18000000,
    description: "Paket all-in dengan dekorasi pelaminan dan rias lengkap.",
    features: [
      "Pelaminan 6 Meter",
      "Tenda Hias 60 Meter",
      "Photo Booth Area",
      "Lighting Dekorasi",
      "Kotak Amplop 2 pcs",
      "Welcome Gate",
      "Welcome Sign",
      "Standing Mirror Selfie",
      "Meja & Kursi Akad",
      "Piring, Sendok, Garpu (100 pcs)",
      "Kursi & Cover 100 pcs",
      "Meja & Alat Parasmanan Set",
      "Rias Pengantin & Touch Up Makeup",
      "Attire Akad 1 Set",
      "Attire Resepsi 2 Set",
      "Melati Fresh Sunda Siger",
      "Henna Art",
      "Softlens",
      "Fake Nails",
      "Attire Orang Tua CPW & CPP",
      "Attire & Makeup Pagar Ayu 2 Orang",
      "Attire & Makeup Parasman 2 Orang",
      "Free Makeup Keluarga 2 Orang",
      "Makeup Ibu Hajat",
    ],
    categories: [
      {
        name: "DEKORASI",
        items: [
          "Pelaminan 6 Meter",
          "Tenda Hias 60 Meter",
          "Photo Booth Area",
          "Lighting Dekorasi",
          "Kotak Amplop 2 pcs",
          "Welcome Gate",
          "Welcome Sign",
          "Standing Mirror Selfie",
          "Meja & Kursi Akad",
          "Piring, Sendok, Garpu (100 pcs)",
          "Kursi & Cover 100 pcs",
          "Meja & Alat Parasmanan Set",
        ],
      },
      {
        name: "MUA & ATTIRE",
        items: [
          "Rias Pengantin & Touch Up Makeup",
          "Attire Akad 1 Set",
          "Attire Resepsi 2 Set",
          "Melati Fresh Sunda Siger",
          "Henna Art",
          "Softlens",
          "Fake Nails",
          "Attire Orang Tua CPW & CPP",
          "Attire & Makeup Pagar Ayu 2 Orang",
          "Attire & Makeup Parasman 2 Orang",
          "Free Makeup Keluarga 2 Orang",
          "Makeup Ibu Hajat",
        ],
      },
    ],
  },
  {
    id: "melati-20",
    name: "ALL PACKAGE MELATI 2",
    price: 20000000,
    description: "Paket all-in dengan dekorasi, rias, dan hiburan jaipong untuk resepsi meriah.",
    isPopular: true,
    features: [
      "Pelaminan 6 Meter",
      "Tenda Hias 60 Meter",
      "Photo Booth Area",
      "Lighting Dekorasi",
      "Kotak Amplop 2 pcs",
      "Welcome Gate",
      "Welcome Sign",
      "Standing Mirror Selfie",
      "Meja & Kursi Akad",
      "Piring, Sendok, Garpu (100 pcs)",
      "Kursi & Cover 100 pcs",
      "Meja & Alat Parasmanan Set",
      "Rias Pengantin & Touch Up Makeup",
      "Attire Akad 1 Set",
      "Attire Resepsi 1 Set",
      "Melati Fresh Sunda Siger",
      "Henna Art",
      "Softlens",
      "Fake Nails",
      "Attire Orang Tua CPW & CPP",
      "Attire & Makeup Pagar Ayu 2 Orang",
      "Attire & Makeup Parasman 2 Orang",
      "Free Makeup Keluarga 2 Orang",
      "Makeup Ibu Hajat",
      "Jaipong Dangdut",
      "Panggung Hiburan Ukuran 4x4 Meter",
      "3 Penyanyi",
      "4 Pemusik",
      "Sound System",
    ],
    categories: [
      {
        name: "DEKORASI",
        items: [
          "Pelaminan 6 Meter",
          "Tenda Hias 60 Meter",
          "Photo Booth Area",
          "Lighting Dekorasi",
          "Kotak Amplop 2 pcs",
          "Welcome Gate",
          "Welcome Sign",
          "Standing Mirror Selfie",
          "Meja & Kursi Akad",
          "Piring, Sendok, Garpu (100 pcs)",
          "Kursi & Cover 100 pcs",
          "Meja & Alat Parasmanan Set",
        ],
      },
      {
        name: "MUA & ATTIRE",
        items: [
          "Rias Pengantin & Touch Up Makeup",
          "Attire Akad 1 Set",
          "Attire Resepsi 1 Set",
          "Melati Fresh Sunda Siger",
          "Henna Art",
          "Softlens",
          "Fake Nails",
          "Attire Orang Tua CPW & CPP",
          "Attire & Makeup Pagar Ayu 2 Orang",
          "Attire & Makeup Parasman 2 Orang",
          "Free Makeup Keluarga 2 Orang",
          "Makeup Ibu Hajat",
        ],
      },
      {
        name: "HIBURAN",
        items: [
          "Jaipong Dangdut",
          "Panggung Hiburan Ukuran 4x4 Meter",
          "3 Penyanyi",
          "4 Pemusik",
          "Sound System",
        ],
      },
    ],
  },
  {
    id: "anggrek",
    name: "ALL PACKAGE ANGGREK",
    price: 22000000,
    description: "Paket all-in dengan dekorasi, rias, dokumentasi foto, dan hiburan.",
    features: [
      "Pelaminan 6 Meter",
      "Tenda Hias 60 Meter",
      "Photo Booth Area",
      "Lighting Dekorasi",
      "Kotak Amplop 2 pcs",
      "Welcome Gate",
      "Welcome Sign",
      "Standing Mirror Selfie",
      "Meja & Kursi Akad",
      "Piring, Sendok, Garpu (100 pcs)",
      "Kursi & Cover 100 pcs",
      "Meja & Alat Parasmanan Set",
      "Rias Pengantin & Touch Up Makeup",
      "Attire Akad 1 Set",
      "Attire Resepsi 1 Set",
      "Melati Fresh Sunda Siger",
      "Henna Art",
      "Softlens",
      "Fake Nails",
      "Attire Orang Tua CPW & CPP",
      "Attire & Makeup Pagar Ayu 2 Orang",
      "Attire & Makeup Parasman 2 Orang",
      "Free Makeup Keluarga 2 Orang",
      "Makeup Ibu Hajat",
      "File Editing",
      "Album Foto",
      "Jaipong Dangdut",
      "Panggung Hiburan Ukuran 4x4 Meter",
      "3 Penyanyi",
      "4 Pemusik",
      "Sound System",
    ],
    categories: [
      {
        name: "DEKORASI",
        items: [
          "Pelaminan 6 Meter",
          "Tenda Hias 60 Meter",
          "Photo Booth Area",
          "Lighting Dekorasi",
          "Kotak Amplop 2 pcs",
          "Welcome Gate",
          "Welcome Sign",
          "Standing Mirror Selfie",
          "Meja & Kursi Akad",
          "Piring, Sendok, Garpu (100 pcs)",
          "Kursi & Cover 100 pcs",
          "Meja & Alat Parasmanan Set",
        ],
      },
      {
        name: "MUA & ATTIRE",
        items: [
          "Rias Pengantin & Touch Up Makeup",
          "Attire Akad 1 Set",
          "Attire Resepsi 1 Set",
          "Melati Fresh Sunda Siger",
          "Henna Art",
          "Softlens",
          "Fake Nails",
          "Attire Orang Tua CPW & CPP",
          "Attire & Makeup Pagar Ayu 2 Orang",
          "Attire & Makeup Parasman 2 Orang",
          "Free Makeup Keluarga 2 Orang",
          "Makeup Ibu Hajat",
        ],
      },
      {
        name: "FOTOGRAFER",
        items: [
          "File Editing",
          "Album Foto",
        ],
      },
      {
        name: "HIBURAN",
        items: [
          "Jaipong Dangdut",
          "Panggung Hiburan Ukuran 4x4 Meter",
          "3 Penyanyi",
          "4 Pemusik",
          "Sound System",
        ],
      },
    ],
  },
  {
    id: "aster",
    name: "ALL PACKAGE ASTER",
    price: 25000000,
    description: "Paket all-in premium dengan adat Sunda, prewedding, dan MC wedding.",
    features: [
      "Pelaminan 6 Meter",
      "Tenda Hias 60 Meter",
      "Photo Booth Area",
      "Lighting Dekorasi",
      "Kotak Amplop 2 pcs",
      "Welcome Gate",
      "Welcome Sign",
      "Standing Mirror Selfie",
      "Meja & Kursi Akad",
      "Piring, Sendok, Garpu (100 pcs)",
      "Kursi & Cover 100 pcs",
      "Meja & Alat Parasman Set",
      "Rias Pengantin & Touch Up Makeup",
      "Attire Akad 1 Set",
      "Attire Resepsi 1 Set",
      "Melati Fresh Sunda Siger",
      "Henna Art",
      "Softlens",
      "Fake Nails",
      "Attire Orang Tua CPW & CPP",
      "Attire & Makeup Pagar Ayu 2 Orang",
      "Attire & Makeup Parasman 2 Orang",
      "Free Makeup Keluarga 2 Orang",
      "Makeup Ibu Hajat",
      "Ambu & Abah",
      "Penari Baksa 1 Orang",
      "Penari 4 Orang",
      "Musik MP3",
      "File Editing",
      "Album Foto",
      "Fotografer (Cetak 16RP & 4 pcs 8RP)",
      "MUA & Free Attire Black Gown",
      "Acara Akad",
      "Sesi Sungkeman",
      "Rangkaian Upacara Adat Sunda",
      "Sawer Pengantin",
      "Jaipong Dangdut",
      "Panggung Hiburan Ukuran 4x4 Meter",
      "3 Penyanyi",
      "4 Pemusik",
      "Sound System",
    ],
    categories: [
      {
        name: "DEKORASI",
        items: [
          "Pelaminan 6 Meter",
          "Tenda Hias 60 Meter",
          "Photo Booth Area",
          "Lighting Dekorasi",
          "Kotak Amplop 2 pcs",
          "Welcome Gate",
          "Welcome Sign",
          "Standing Mirror Selfie",
          "Meja & Kursi Akad",
          "Piring, Sendok, Garpu (100 pcs)",
          "Kursi & Cover 100 pcs",
          "Meja & Alat Parasman Set",
        ],
      },
      {
        name: "MUA & ATTIRE",
        items: [
          "Rias Pengantin & Touch Up Makeup",
          "Attire Akad 1 Set",
          "Attire Resepsi 1 Set",
          "Melati Fresh Sunda Siger",
          "Henna Art",
          "Softlens",
          "Fake Nails",
          "Attire Orang Tua CPW & CPP",
          "Attire & Makeup Pagar Ayu 2 Orang",
          "Attire & Makeup Parasman 2 Orang",
          "Free Makeup Keluarga 2 Orang",
          "Makeup Ibu Hajat",
        ],
      },
      {
        name: "GALURA",
        items: [
          "Ambu & Abah",
          "Penari Baksa 1 Orang",
          "Penari 4 Orang",
          "Musik MP3",
        ],
      },
      {
        name: "FOTOGRAFER",
        items: [
          "File Editing",
          "Album Foto",
        ],
      },
      {
        name: "PREWEDDING",
        items: [
          "Fotografer (Cetak 16RP & 4 pcs 8RP)",
          "MUA & Free Attire Black Gown",
        ],
      },
      {
        name: "MC WEDDING",
        items: [
          "Acara Akad",
          "Sesi Sungkeman",
          "Rangkaian Upacara Adat Sunda",
          "Sawer Pengantin",
        ],
      },
      {
        name: "HIBURAN",
        items: [
          "Jaipong Dangdut",
          "Panggung Hiburan Ukuran 4x4 Meter",
          "3 Penyanyi",
          "4 Pemusik",
          "Sound System",
        ],
      },
    ],
  },
  {
    id: "edelweis",
    name: "ALL PACKAGE EDELWEIS",
    price: 35000000,
    description: "Paket all-in eksklusif dengan layanan lengkap untuk pernikahan mewah & sempurna.",
    features: [
      "Pelaminan 8 Meter",
      "Tenda Hias 120 Meter",
      "Photo Booth Area",
      "Lighting Dekorasi",
      "Kotak Amplop 2 pcs",
      "Welcome Gate",
      "Welcome Sign",
      "Standing Mirror Selfie",
      "Meja & Kursi Akad",
      "Piring, Sendok, Garpu (100 pcs)",
      "Kursi & Cover 100 pcs",
      "Meja & Alat Parasman Set",
      "Rias Pengantin & Touch Up Makeup",
      "Attire Akad 1 Set",
      "Attire Resepsi 2 Set",
      "Melati Fresh Sunda Siger",
      "Henna Art",
      "Softlens",
      "Fake Nails",
      "Attire Orang Tua CPW & CPP",
      "Attire & Makeup Pagar Ayu 2 Orang",
      "Attire & Makeup Parasman 2 Orang",
      "Free Makeup Keluarga 2 Orang",
      "Makeup Ibu Hajat",
      "Makeup Besan",
      "Ambu & Abah",
      "Penari Baksa 1 Orang",
      "Penari 4 Orang",
      "Musik Live",
      "File Editing",
      "Album Foto",
      "Cinematic Video",
      "Fotografer (Cetak 16RP & 4 pcs 8RP)",
      "MUA & Free Attire Black Gown",
      "Acara Akad",
      "Sesi Sungkeman",
      "Rangkaian Upacara Adat Sunda",
      "Sawer Pengantin",
      "Kirab Resepsi",
      "Jaipong Dangdut",
      "Panggung Hiburan Ukuran 4x4 Meter",
      "3 Penyanyi",
      "4 Pemusik",
      "Sound System",
    ],
    categories: [
      {
        name: "DEKORASI",
        items: [
          "Pelaminan 8 Meter",
          "Tenda Hias 120 Meter",
          "Photo Booth Area",
          "Lighting Dekorasi",
          "Kotak Amplop 2 pcs",
          "Welcome Gate",
          "Welcome Sign",
          "Standing Mirror Selfie",
          "Meja & Kursi Akad",
          "Piring, Sendok, Garpu (100 pcs)",
          "Kursi & Cover 100 pcs",
          "Meja & Alat Parasman Set",
        ],
      },
      {
        name: "MUA & ATTIRE",
        items: [
          "Rias Pengantin & Touch Up Makeup",
          "Attire Akad 1 Set",
          "Attire Resepsi 2 Set",
          "Melati Fresh Sunda Siger",
          "Henna Art",
          "Softlens",
          "Fake Nails",
          "Attire Orang Tua CPW & CPP",
          "Attire & Makeup Pagar Ayu 2 Orang",
          "Attire & Makeup Parasman 2 Orang",
          "Free Makeup Keluarga 2 Orang",
          "Makeup Ibu Hajat",
          "Makeup Besan",
        ],
      },
      {
        name: "GALURA",
        items: [
          "Ambu & Abah",
          "Penari Baksa 1 Orang",
          "Penari 4 Orang",
          "Musik Live",
        ],
      },
      {
        name: "FOTOGRAFER",
        items: [
          "File Editing",
          "Album Foto",
          "Cinematic Video",
        ],
      },
      {
        name: "PREWEDDING",
        items: [
          "Fotografer (Cetak 16RP & 4 pcs 8RP)",
          "MUA & Free Attire Black Gown",
        ],
      },
      {
        name: "MC WEDDING",
        items: [
          "Acara Akad",
          "Sesi Sungkeman",
          "Rangkaian Upacara Adat Sunda",
          "Sawer Pengantin",
          "Kirab Resepsi",
        ],
      },
      {
        name: "HIBURAN",
        items: [
          "Jaipong Dangdut",
          "Panggung Hiburan Ukuran 4x4 Meter",
          "3 Penyanyi",
          "4 Pemusik",
          "Sound System",
        ],
      },
    ],
  },
];

export const testimonials: Testimonial[] = [
  {
    id: "1",
    name: "Sarah & Andi",
    role: "Pengantin",
    avatar: "/images/testimonial-1.jpg",
    message:
      "Makep & dekorasinya flawless banget! Dinar Wedding bikin aku pede di hari pernikahan. Hasilnya natural dan tahan seharian.",
    rating: 5,
  },
  {
    id: "2",
    name: "Rina",
    role: "Ibu Pengantin",
    avatar: "/images/testimonial-2.jpg",
    message:
      "Pelayanan ramah dan profesional. Hasil riasan dan dekorasinya elegant banget, cocok banget sama tema pernikahan.",
    rating: 5,
  },
  {
    id: "3",
    name: "Dian & Budi",
    role: "Pengantin",
    avatar: "/images/testimonial-3.jpg",
    message:
      "Mulai dari trial sampe hari H, semua lancar. Timnya tepat waktu dan bikin riasan & dekorasi yang sempurna.",
    rating: 5,
  },
];

const CLOUD_BASE = "https://res.cloudinary.com/inkara-id/image/upload";

export const galleryImages: GalleryImage[] = [
  // MakeUp
  { id: "mu-1", src: `${CLOUD_BASE}/dinar-wedding/gallery/MakeUp/1.png`, alt: "Rias pengantin natural", category: "makeup" },
  { id: "mu-2", src: `${CLOUD_BASE}/dinar-wedding/gallery/MakeUp/2.png`, alt: "Makeup pengantin elegan", category: "makeup" },
  { id: "mu-3", src: `${CLOUD_BASE}/dinar-wedding/gallery/MakeUp/3.png`, alt: "Rias pengantin classic", category: "makeup" },
  { id: "mu-4", src: `${CLOUD_BASE}/dinar-wedding/gallery/MakeUp/4.png`, alt: "Makeup pengantin modern", category: "makeup" },
  { id: "mu-5", src: `${CLOUD_BASE}/dinar-wedding/gallery/MakeUp/5.png`, alt: "Rias pengantin glowing", category: "makeup" },
  { id: "mu-6", src: `${CLOUD_BASE}/dinar-wedding/gallery/MakeUp/6.png`, alt: "Makeup pengantin soft", category: "makeup" },
  { id: "mu-7", src: `${CLOUD_BASE}/dinar-wedding/gallery/MakeUp/7.jpg`, alt: "Rias pengantin premium", category: "makeup" },
  { id: "mu-8", src: `${CLOUD_BASE}/dinar-wedding/gallery/MakeUp/8.png`, alt: "Makeup pengantin tradisional", category: "makeup" },
  // Akad
  { id: "ak-1", src: `${CLOUD_BASE}/dinar-wedding/gallery/Akad/001.jpg`, alt: "Proses akad nikah", category: "akad" },
  { id: "ak-2", src: `${CLOUD_BASE}/dinar-wedding/gallery/Akad/002.jpg`, alt: "Momen akad sakral", category: "akad" },
  { id: "ak-3", src: `${CLOUD_BASE}/dinar-wedding/gallery/Akad/003.jpg`, alt: "Pengantin saat akad", category: "akad" },
  { id: "ak-4", src: `${CLOUD_BASE}/dinar-wedding/gallery/Akad/004.jpg`, alt: "Sesi akad penuh haru", category: "akad" },
  { id: "ak-5", src: `${CLOUD_BASE}/dinar-wedding/gallery/Akad/005.jpg`, alt: "Prosesi ijab kabul", category: "akad" },
  { id: "ak-7", src: `${CLOUD_BASE}/dinar-wedding/gallery/Akad/007.jpg`, alt: "Momen akad bahagia", category: "akad" },
  { id: "ak-8", src: `${CLOUD_BASE}/dinar-wedding/gallery/Akad/008.jpg`, alt: "Akad nikah khidmat", category: "akad" },
  { id: "ak-9", src: `${CLOUD_BASE}/dinar-wedding/gallery/Akad/009.jpg`, alt: "Pengantin saat akad", category: "akad" },
  // Dekorasi
  { id: "dek-1", src: `${CLOUD_BASE}/dinar-wedding/gallery/Dekorasi/011.jpg`, alt: "Dekorasi pelaminan", category: "dekorasi" },
  { id: "dek-2", src: `${CLOUD_BASE}/dinar-wedding/gallery/Dekorasi/012.jpg`, alt: "Hiasan dekorasi mewah", category: "dekorasi" },
  { id: "dek-3", src: `${CLOUD_BASE}/dinar-wedding/gallery/Dekorasi/013.jpg`, alt: "Dekorasi panggung", category: "dekorasi" },
  { id: "dek-4", src: `${CLOUD_BASE}/dinar-wedding/gallery/Dekorasi/014.jpg`, alt: "Dekorasi pengantin", category: "dekorasi" },
  { id: "dek-5", src: `${CLOUD_BASE}/dinar-wedding/gallery/Dekorasi/015.jpg`, alt: "Dekorasi pelaminan classic", category: "dekorasi" },
  { id: "dek-6", src: `${CLOUD_BASE}/dinar-wedding/gallery/Dekorasi/016.jpg`, alt: "Dekorasi bunga indah", category: "dekorasi" },
  { id: "dek-7", src: `${CLOUD_BASE}/dinar-wedding/gallery/Dekorasi/017.jpg`, alt: "Dekorasi resepsi", category: "dekorasi" },
  { id: "dek-8", src: `${CLOUD_BASE}/dinar-wedding/gallery/Dekorasi/018.jpg`, alt: "Dekorasi pernikahan", category: "dekorasi" },
];

export const faqItems = [
  {
    question: "Bagaimana cara booking?",
    answer:
      "Anda bisa booking langsung via WhatsApp dengan klik tombol Booking di website kami. Kami akan merespon dalam 1x24 jam.",
  },
  {
    question: "Apakah ada trial makeup?",
    answer:
      "Ya, setiap paket sudah termasuk trial makeup. Untuk paket Basic 1x trial, Premium 1x trial, dan Exclusive 2x trial.",
  },
  {
    question: "Berapa lama proses rias?",
    answer:
      "Proses rias pengantin biasanya memakan waktu 2-3 jam, tergantung kompleksitas riasan dan sanggul.",
  },
  {
    question: "Apakah menyediakan dekorasi sendiri?",
    answer:
      "Ya, kami memiliki tim dekorasi profesional yang siap mewujudkan dekorasi impian Anda, mulai dari pelaminan hingga venue resepsi.",
  },
  {
    question: "Apakah melayani luar kota?",
    answer:
      "Ya, kami melayani rias & dekorasi luar kota dengan tambahan biaya transportasi dan akomodasi.",
  },
  {
    question: "Bisakah request model riasan atau tema dekorasi tertentu?",
    answer:
      "Tentu! Kami akan diskusikan saat konsultasi untuk mendapatkan hasil riasan dan dekorasi yang sesuai dengan keinginan Anda.",
  },
];

export const services = [
  {
    title: "Rias Pengantin",
    description: "Rias wajah pengantin dengan teknik flawless dan tahan lama.",
    icon: "makeup",
  },
  {
    title: "Trial Makeup",
    description: "Sesi percobaan rias CPW dan CPP sebelum hari H.",
    icon: "trial",
  },
  {
    title: "Rias Ibu & Bridesmaid",
    description: "Rias untuk ibu dan pendamping pengantin.",
    icon: "bridesmaid",
  },
  {
    title: "Dekorasi Resepsi",
    description: "Dekorasi venue resepsi yang mewah dan berkesan.",
    icon: "dekorasi",
  },
];
